package sshconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"github.com/sshgo/sshgo/internal/config"
)

func GenerateSSHConfig(cfg *config.Config, dryRun bool) error {
	var buf strings.Builder
	buf.WriteString("# Generated by sshgo - DO NOT EDIT MANUALLY\n\n")
	for _, p := range cfg.Profiles {
		buf.WriteString(fmt.Sprintf("Host %s\n", p.Name))
		buf.WriteString(fmt.Sprintf("    HostName %s\n", p.Host))
		buf.WriteString(fmt.Sprintf("    User %s\n", p.User))
		if p.Port != 0 && p.Port != 22 {
			buf.WriteString(fmt.Sprintf("    Port %d\n", p.Port))
		}
		if p.IdentityFile != "" {
			buf.WriteString(fmt.Sprintf("    IdentityFile %s\n", p.IdentityFile))
		}
		if len(p.JumpHosts) > 0 {
			var jumps []string
			for _, j := range p.JumpHosts {
				addr := j.User + "@" + j.Host
				if j.Port != 0 && j.Port != 22 {
					addr = fmt.Sprintf("%s@%s:%d", j.User, j.Host, j.Port)
				}
				jumps = append(jumps, addr)
			}
			buf.WriteString(fmt.Sprintf("    ProxyJump %s\n", strings.Join(jumps, ",")))
		}
		for _, f := range p.ForwardPorts {
			buf.WriteString(fmt.Sprintf("    LocalForward %d %s:%d\n", f.LocalPort, f.RemoteHost, f.RemotePort))
		}
		if p.KeepaliveInterval > 0 {
			buf.WriteString(fmt.Sprintf("    ServerAliveInterval %d\n", p.KeepaliveInterval))
		}
		if p.ServerAliveCount > 0 {
			buf.WriteString(fmt.Sprintf("    ServerAliveCountMax %d\n", p.ServerAliveCount))
		}
		buf.WriteString("\n")
	}
	if dryRun {
		fmt.Print(buf.String())
		return nil
	}
	home, _ := os.UserHomeDir()
	sshConfigPath := filepath.Join(home, ".ssh", "config")
	if orig, err := os.ReadFile(sshConfigPath); err == nil {
		if err := os.WriteFile(sshConfigPath+".sshgo.bak", orig, 0600); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: failed to backup ~/.ssh/config: %v\n", err)
		}
	}
	existingContent := ""
	if orig, err := os.ReadFile(sshConfigPath); err == nil {
		lines := strings.Split(string(orig), "\n")
		var kept []string
		inSshgoBlock := false
		for _, line := range lines {
			if strings.Contains(line, "# Generated by sshgo") {
				inSshgoBlock = true
				continue
			}
			if inSshgoBlock && line == "" {
				inSshgoBlock = false
				continue
			}
			if !inSshgoBlock {
				kept = append(kept, line)
			}
		}
		existingContent = strings.Join(kept, "\n")
		if strings.TrimSpace(existingContent) != "" {
			existingContent += "\n\n"
		}
	}
	fullContent := existingContent + buf.String()
	if err := os.WriteFile(sshConfigPath, []byte(fullContent), 0600); err != nil {
		return fmt.Errorf("failed to write ~/.ssh/config: %w", err)
	}
	fmt.Println("[OK] Synced to ~/.ssh/config")
	return nil
}